package com.acme.empexpenses.employee_task_approval;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class employeeDO implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "empID")
   private java.lang.String empID;
   @org.kie.api.definition.type.Label(value = "empName")
   private java.lang.String empName;
   @org.kie.api.definition.type.Label(value = "empDept")
   private java.lang.Integer empDept;
   @org.kie.api.definition.type.Label(value = "empDesignation")
   private java.lang.String empDesignation;

   public employeeDO()
   {
   }

   public java.lang.String getEmpID()
   {
      return this.empID;
   }

   public void setEmpID(java.lang.String empID)
   {
      this.empID = empID;
   }

   public java.lang.String getEmpName()
   {
      return this.empName;
   }

   public void setEmpName(java.lang.String empName)
   {
      this.empName = empName;
   }

   public java.lang.Integer getEmpDept()
   {
      return this.empDept;
   }

   public void setEmpDept(java.lang.Integer empDept)
   {
      this.empDept = empDept;
   }

   public java.lang.String getEmpDesignation()
   {
      return this.empDesignation;
   }

   public void setEmpDesignation(java.lang.String empDesignation)
   {
      this.empDesignation = empDesignation;
   }

   public employeeDO(java.lang.String empID, java.lang.String empName,
         java.lang.Integer empDept, java.lang.String empDesignation)
   {
      this.empID = empID;
      this.empName = empName;
      this.empDept = empDept;
      this.empDesignation = empDesignation;
   }

}