package com.acme.empexpenses.employee_task_approval;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class requestDO implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("reqID")
   private java.lang.String reqID;
   @org.kie.api.definition.type.Label("reqDetail")
   private java.lang.String reqDetail;
   @org.kie.api.definition.type.Label("cost")
   private java.lang.Integer cost;
   @org.kie.api.definition.type.Label("priority")
   private java.lang.Integer priority;

   private java.lang.Boolean approved;

   public requestDO()
   {
   }

   public java.lang.String getReqID()
   {
      return this.reqID;
   }

   public void setReqID(java.lang.String reqID)
   {
      this.reqID = reqID;
   }

   public java.lang.String getReqDetail()
   {
      return this.reqDetail;
   }

   public void setReqDetail(java.lang.String reqDetail)
   {
      this.reqDetail = reqDetail;
   }

   public java.lang.Integer getCost()
   {
      return this.cost;
   }

   public void setCost(java.lang.Integer cost)
   {
      this.cost = cost;
   }

   public java.lang.Integer getPriority()
   {
      return this.priority;
   }

   public void setPriority(java.lang.Integer priority)
   {
      this.priority = priority;
   }

   public java.lang.Boolean getApproved()
   {
      return this.approved;
   }

   public void setApproved(java.lang.Boolean approved)
   {
      this.approved = approved;
   }

   public requestDO(java.lang.String reqID, java.lang.String reqDetail,
         java.lang.Integer cost, java.lang.Integer priority,
         java.lang.Boolean approved)
   {
      this.reqID = reqID;
      this.reqDetail = reqDetail;
      this.cost = cost;
      this.priority = priority;
      this.approved = approved;
   }

}