apiVersion: v1
kind: Template
labels:
  template: processserver63-sso-mysql-persistent-s2i
metadata:
  annotations:
    description: Application template for Red Hat JBoss BPMS 6.3 process server applications
      built using S2I. Uses MySQL for persistence and persistent storage.
    iconClass: icon-jboss
    tags: processserver,java,jboss,xpaas
  name: processserver63-sso-mysql-persistent-s2i
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The web server's http port.
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - port: 8443
      targetPort: 8443
    selector:
      deploymentConfig: ${APPLICATION_NAME}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The database server's port.
    labels:
      application: ${APPLICATION_NAME}  
    name: ${APPLICATION_NAME}-mysql
  spec:
    ports:
    - port: 3306
      targetPort: 3306
    selector:
      deploymentConfig: ${APPLICATION_NAME}-mysql
- apiVersion: v1
  kind: Route
  id: ${APPLICATION_NAME}-https
  metadata:
    annotations:
      description: Route for application's https service.
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    to:
      kind: Service
      name: ${APPLICATION_NAME}
    tls:
      termination: "passthrough"
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: KIE_CONTAINER_DEPLOYMENT
          value: ${KIE_CONTAINER_DEPLOYMENT}
        - name: KIE_CONTAINER_REDIRECT_ENABLED
          value: ${KIE_CONTAINER_REDIRECT_ENABLED}
        - name: MAVEN_MIRROR_URL
          value: ${MAVEN_MIRROR_URL}
        forcePull: true
        from:
          kind: ImageStreamTag
          name: jboss-processserver63:latest
          namespace: ${IMAGE_STREAM_NAMESPACE}
      type: Source
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - generic:
        secret: ${GENERIC_WEBHOOK_SECRET}
      type: Generic
    - type: ImageChange
      imageChange: {}      
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      deploymentConfig: ${APPLICATION_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          application: ${APPLICATION_NAME}
          deploymentConfig: ${APPLICATION_NAME}
        name: ${APPLICATION_NAME}
      spec:
        containers:
        - name: ${APPLICATION_NAME}
          image: ${APPLICATION_NAME}
          imagePullPolicy: Always
          volumeMounts:
          - name: processserver-keystore-volume
            mountPath: /etc/processserver-secret-volume
            readOnly: true          
          env:
          - name: KIE_CONTAINER_DEPLOYMENT
            value: ${KIE_CONTAINER_DEPLOYMENT}
          - name: KIE_SERVER_PROTOCOL
            value: ${KIE_SERVER_PROTOCOL}
          - name: KIE_SERVER_PORT
            value: ${KIE_SERVER_PORT}
          - name: KIE_SERVER_USER
            value: ${KIE_SERVER_USER}
          - name: KIE_SERVER_PASSWORD
            value: ${KIE_SERVER_PASSWORD}
          - name: KIE_CONTAINER_REDIRECT_ENABLED
            value: ${KIE_CONTAINER_REDIRECT_ENABLED}
          - name: KIE_SERVER_BYPASS_AUTH_USER
            value: ${KIE_SERVER_BYPASS_AUTH_USER}
          - name: KIE_SERVER_HT_CALLBACK
            value: ${KIE_SERVER_HT_CALLBACK}
          - name: KIE_SERVER_PERSISTENCE_DIALECT
            value: ${KIE_SERVER_PERSISTENCE_DIALECT}
          - name: HTTPS_KEYSTORE_DIR
            value: /etc/processserver-secret-volume
          - name: HTTPS_KEYSTORE
            value: ${HTTPS_KEYSTORE}
          - name: HTTPS_NAME
            value: ${HTTPS_NAME}
          - name: HTTPS_PASSWORD
            value: ${HTTPS_PASSWORD}
          - name: DB_SERVICE_PREFIX_MAPPING
            value: ${APPLICATION_NAME}-mysql=DB,${APPLICATION_NAME}-mysql=QUARTZ
          - name: DB_JNDI
            value: ${DB_JNDI}
          - name: DB_USERNAME
            value: ${DB_USERNAME}
          - name: DB_PASSWORD
            value: ${DB_PASSWORD}
          - name: DB_DATABASE
            value: ${DB_DATABASE}
          - name: QUARTZ_JNDI
            value: ${DB_JNDI}NotManaged
          - name: QUARTZ_USERNAME
            value: ${DB_USERNAME}
          - name: QUARTZ_PASSWORD
            value: ${DB_PASSWORD}
          - name: QUARTZ_DATABASE
            value: ${DB_DATABASE}
          - name: QUARTZ_JTA
            value: 'false'
          - name: QUARTZ_NONXA
            value: 'true'
          ports:
          - name: jolokia
            containerPort: 8778
            protocol: TCP
          - name: https
            containerPort: 8443
            protocol: TCP
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - /opt/eap/bin/livenessProbe_eap.sh
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - /opt/eap/bin/readinessProbe_eap.sh
            periodSeconds: 30
        terminationGracePeriodSeconds: 60
        volumes:
        - name: processserver-keystore-volume
          secret:
            secretName: ${HTTPS_SECRET}        
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStream
          name: ${APPLICATION_NAME}
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-mysql
  spec:
    replicas: 1
    selector:
      deploymentConfig: ${APPLICATION_NAME}-mysql
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          application: ${APPLICATION_NAME}
          deploymentConfig: ${APPLICATION_NAME}-mysql
        name: ${APPLICATION_NAME}-mysql
      spec:
        containers:
        - name: ${APPLICATION_NAME}-mysql
          image: mysql
          imagePullPolicy: Always
          env:
          - name: MYSQL_USER
            value: ${DB_USERNAME}
          - name: MYSQL_PASSWORD
            value: ${DB_PASSWORD}
          - name: MYSQL_DATABASE
            value: ${DB_DATABASE}
          - name: MYSQL_LOWER_CASE_TABLE_NAMES
            value: ${MYSQL_LOWER_CASE_TABLE_NAMES}
          ports:
          - containerPort: 3306
            protocol: TCP
          volumeMounts:
          - mountPath: /var/lib/mysql/data
            name: ${APPLICATION_NAME}-mysql-data
        volumes:
        - name: ${APPLICATION_NAME}-mysql-data
          persistentVolumeClaim:
            claimName: ${APPLICATION_NAME}-mysql-pvc
        terminationGracePeriodSeconds: 60
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}-mysql
        from:
          kind: ImageStreamTag
          name: mysql:latest
          namespace: openshift
    - type: ConfigChange
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${APPLICATION_NAME}-mysql-pvc
    labels:
      application: ${APPLICATION_NAME}
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}
parameters:
- name: APPLICATION_NAME
  description: The name for the application.
  required: true
- name: KIE_SERVER_PROTOCOL
  description: The protocol to access the KIE Server REST interface.
  value: https
  required: false
- name: KIE_SERVER_PORT
  description: The port to access the KIE Server REST interface.
  value: '8443'
  required: false
- name: HTTPS_SECRET
  description: The name of the secret containing the keystore file.
  value: processserver-app-secret
  required: false
- name: HTTPS_KEYSTORE
  description: The name of the keystore file within the secret.
  value: keystore.jks
  required: false
- name: HTTPS_NAME
  description: The name associated with the server certificate.
  value: redhat
  required: false
- name: HTTPS_PASSWORD
  description: The password for the keystore and certificate (e.g. mykeystorepass).
  required: false
- name: KIE_CONTAINER_DEPLOYMENT
  description: 'The KIE Container deployment configuration in format: containerId=groupId:artifactId:version|c2=g2:a2:v2'
  required: false
- name: KIE_CONTAINER_REDIRECT_ENABLED
  description : Enable redirect functionality for KIE containers.
  required: false
- name: KIE_SERVER_USER
  description: The user name to access the KIE Server REST or JMS interface.
  value: kieserver
  required: false
- name: KIE_SERVER_PASSWORD
  description: The password to access the KIE Server REST or JMS interface. Must be
    different than username; must not be root, admin, or administrator; must contain
    at least 8 characters, 1 alphabetic character(s), 1 digit(s), and 1 non-alphanumeric
    symbol(s).
  from: '[a-zA-Z]{6}[0-9]{1}!'
  generate: expression
  required: false
- name: KIE_SERVER_BYPASS_AUTH_USER
  description: Bypass authenticated user
  required: false
- name: KIE_SERVER_HT_CALLBACK
  description: mechanism to use for HT callback implementation
  required: false
- name: KIE_SERVER_PERSISTENCE_DIALECT
  description: Hibernate persistence dialect.
  value: org.hibernate.dialect.MySQL5Dialect
  required: false
- name: DB_USERNAME
  description: "Database user name"
  from: 'user[a-zA-Z0-9]{3}'
  generate: expression
  required: true
- name: DB_PASSWORD
  description: Database user password.
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  required: true
- name: DB_JNDI
  description: Database JNDI name used by application to resolve the datasource, e.g. java:/jboss/datasources/ExampleDS.
  value: java:jboss/datasources/ExampleDS
  required: false
- name: DB_DATABASE
  description: Database name.
  value: bpms
  required: true
- name: MYSQL_LOWER_CASE_TABLE_NAMES
  description: Sets how the table names are stored and compared.
  value: '1'
  required: false
- name: HOSTNAME_HTTP
  description: 'Custom hostname for http service route.  Leave blank for default hostname,
    e.g.: <application-name>-<project>.<default-domain-suffix>'
- name: SOURCE_REPOSITORY_URL
  description: Git source URI for application
  required: true
- name: SOURCE_REPOSITORY_REF
  description: Git branch/tag reference
  value: master
  required: false
- name: CONTEXT_DIR
  description: Path within Git project to build; empty for root project directory.
  required: false
- name: GITHUB_WEBHOOK_SECRET
  description: GitHub trigger secret
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  required: true
- name: GENERIC_WEBHOOK_SECRET
  description: Generic build trigger secret
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  required: true
- name: IMAGE_STREAM_NAMESPACE
  description: Namespace in which the ImageStreams for Red Hat Middleware images are
    installed. These ImageStreams are normally installed in the openshift namespace.
    You should only need to modify this if you've installed the ImageStreams in a
    different namespace/project.
  value: openshift
  required: true
- name: MAVEN_MIRROR_URL
  description: The URL of the maven mirror
  required: false
- name: VOLUME_CAPACITY
  description: Volume space available for data, e.g. 512Mi, 2Gi
  value: 512Mi
  required: true